[module]
[[module.mounts]]
# Workaround for https://github.com/gohugoio/hugo/issues/6945
source = "assets/scss/Font-Awesome/_vendor"
target = "assets/scss/Font-Awesome/vendor"
[[module.imports]]
path="github.com/FortAwesome/Font-Awesome"
[[module.imports.mounts]]
source = "scss"
target = "assets/vendor/Font-Awesome"